# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20180503_0907'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='movie',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_is_active',
            new_name='is_active',
        ),
    ]
