# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20180504_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
